### ISSUE TITLE
Upgrade e2e tests for Chrome 76+ and protractor

### ISSUE THREAD

**Issue by MirkoBrandnerContrast** [juice-shop/juice-shop#1192]
Chrome 76 has broken Protractor and e2e tests. Just WebDrivers updates does not help an then it gets difficult. Therefore, I file this new request.

**Comment by bkimminich** [comment]
Can you provide some information about your test environment? Our last build on Travis-CI ran with `google-chrome-stable (76.0.3809.100-1)` and all e2e tests passed for the upcoming v9.0.0 release.

**Comment by MirkoBrandnerContrast** [comment]
Hallo,

Thanks for your quick response: I tried in dockerized Ubuntu as well as in MacOS 10.16.6 using npm run e2e



  *   npm -v 6.4.1
  *   node -v v10.15.3


I have run the webdriver update command already. This is what I get:



> juice-shop@8.6.2 e2e /private/tmp/juice-shop-dockerized

> node test/e2eTests.js



info: Detected Node.js version v10.15.3 (OK)

info: Detected OS darwin (OK)

info: Detected CPU x64 (OK)

info: Required file index.html is present (OK)

info: Required file main.js is present (OK)

info: Required file polyfills.js is present (OK)

info: Required file runtime.js is present (OK)

info: Required file vendor.js is present (OK)

info: Configuration default validated (OK)

info: Port 3000 is available (OK)

[17:17:34] I/launcher - Running 1 instances of WebDriver



[17:17:34] I/direct - Using ChromeDriver directly...



[17:17:36] E/launcher - session not created: Chrome version must be between 71 and 75

  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.6 x86_64)



[17:17:36] E/launcher - SessionNotCreatedError: session not created: Chrome version must be between 71 and 75

  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.6 x86_64)

    at Object.checkLegacyResponse (/private/tmp/juice-shop-dockerized/node_modules/selenium-webdriver/lib/error.js:546:15)

    at parseHttpResponse (/private/tmp/juice-shop-dockerized/node_modules/selenium-webdriver/lib/http.js:509:13)

    at doSend.then.response (/private/tmp/juice-shop-dockerized/node_modules/selenium-webdriver/lib/http.js:441:30)

    at process._tickCallback (internal/process/next_tick.js:68:7)

From: Task: WebDriver.createSession()

    at Function.createSession (/private/tmp/juice-shop-dockerized/node_modules/selenium-webdriver/lib/webdriver.js:769:24)

    at Function.createSession (/private/tmp/juice-shop-dockerized/node_modules/selenium-webdriver/chrome.js:761:15)

    at Direct.getNewDriver (/private/tmp/juice-shop-dockerized/node_modules/protractor/built/driverProviders/direct.js:77:33)

    at Runner.createBrowser (/private/tmp/juice-shop-dockerized/node_modules/protractor/built/runner.js:195:43)

    at q.then.then (/private/tmp/juice-shop-dockerized/node_modules/protractor/built/runner.js:339:29)

    at _fulfilled (/private/tmp/juice-shop-dockerized/node_modules/q/q.js:834:54)

    at /private/tmp/juice-shop-dockerized/node_modules/q/q.js:863:30

    at Promise.promise.promiseDispatch (/private/tmp/juice-shop-dockerized/node_modules/q/q.js:796:13)

    at /private/tmp/juice-shop-dockerized/node_modules/q/q.js:556:49

    at runSingle (/private/tmp/juice-shop-dockerized/node_modules/q/q.js:137:13)

    at flush (/private/tmp/juice-shop-dockerized/node_modules/q/q.js:125:13)

    at process._tickCallback (internal/process/next_tick.js:61:11)

    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)

    at startup (internal/bootstrap/node.js:283:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)



[17:17:36] E/launcher - Process exited with error code 199



Protractor exited with code 199 (FAILED)



Thanks, Mirko

Mirko Brandner <mailto:mirko.brandner@contrastsecurity.com> | Senior Sales Engineer DACH
Contrast Security, Inc.<https://www.contrastsecurity.com/>
<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.contrastsecurity.com_&d=DwMGaQ&c=BNNF-YNv0CLLslhP2Bcx5Q&r=GAsGzPUD-BSVfWHkG-5HV32yHFrp05nRKZg7dk_83Ws&m=qeuClKCSSgYURKLlZBxV80wgWRN63Kkdx7JQW5Lf2hI&s=NoSRC-wU-sLUGC0Bh7qLxJKcUC5AQLOjh8458tNcY4c&e=>+49 152 32014643 (mobile)
Welcome to the Era of Self-Protecting Software

**Comment by MirkoBrandnerContrast** [comment]
Hey sorry,
 
please ignore. For some reason, it works in MacOs now. I try to get things running in a docker image again now. I tried checking out from scratch in a clean place (which I had done before, of course). Maybe protractor update gave me the wrong thing. I wonder about the right way to run the update for webdrivers.
 
find . -name webdriver-manager
./node_modules/.bin/webdriver-manager
./node_modules/protractor/bin/webdriver-manager
./node_modules/protractor/node_modules/.bin/webdriver-manager
./node_modules/protractor/node_modules/webdriver-manager
./node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager
 
Please, close this issue. I am sorry. Will be more careful next time. Mirko

**Comment by bkimminich** [comment]
No problem... btw, I just checked on Windows with `master` branch and all worked fine as well:

```
$ npm run protractor

> juice-shop@8.7.3 preprotractor C:\Data\GitHub\juice-shop
> webdriver-manager update --gecko false

[10:50:02] I/config_source - curl -oC:\Data\GitHub\juice-shop\node_modules\protractor\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[10:50:02] I/config_source - curl -oC:\Data\GitHub\juice-shop\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[10:50:03] I/update - chromedriver: file exists C:\Data\GitHub\juice-shop\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.46.zip
[10:50:03] I/update - chromedriver: unzipping chromedriver_2.46.zip
[10:50:03] I/update - chromedriver: chromedriver_2.46.exe up to date
[10:50:04] I/downloader - curl -oC:\Data\GitHub\juice-shop\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-4.0.0-alpha-2.zip.jar https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-2.zip

> juice-shop@8.7.3 protractor C:\Data\GitHub\juice-shop
> npm run e2e


> juice-shop@8.7.3 e2e C:\Data\GitHub\juice-shop
> node test/e2eTests.js

info: Detected Node.js version v10.15.3 (OK)
info: Detected OS win32 (OK)
info: Detected CPU x64 (OK)
info: Required file index.html is present (OK)
info: Required file main.js is present (OK)
info: Required file polyfills.js is present (OK)
info: Required file runtime.js is present (OK)
info: Required file vendor.js is present (OK)
info: Configuration default validated (OK)
info: Port 3000 is available (OK)
info: Server listening on port 3000
[10:50:29] I/launcher - Running 1 instances of WebDriver

[10:50:29] I/direct - Using ChromeDriver directly...

Started
```
