### ISSUE TITLE
Permission denied while running in kubernetes

### ISSUE THREAD

**Issue by ramakrishnateja** [juice-shop/juice-shop#1201]
Hi ,

I am trying to deploy this in kubernetes and getting a failure of permissions. Please find the deployment below and the exception I am getting.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  labels:
    app: juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000
          name: http

Exception:

(node:17) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile '/juice-shop/data/static/legal.md' -> '/juice-shop/ftp/legal.md'
    at Object.copyFileSync (fs.js:1773:3)
    at restoreOverwrittenFilesWithOriginals (/juice-shop/lib/startup/restoreOverwrittenFilesWithOriginals.js:5:6)
    at Object.<anonymous> (/juice-shop/server.js:120:62)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /juice-shop/app.js:2:18
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by J12934** [comment]
Hi 👋
yup thats a current issues, but a fix is on the way: 
#1199.

Thanks for reporting it 👍

**Comment by ramakrishnateja** [comment]
Wow that was a quick response. Thanks

**Comment by bkimminich** [comment]
Merged #1199.
