### ISSUE TITLE
Unable to launch the web application with npm strart[🐛] 

### ISSUE THREAD

**Issue by Infinity-Intellect** [juice-shop/juice-shop#1394]
I'm getting the following error when I run npm start.
I'm using a pre-packaged distribution.
```
> juice-shop@10.3.2 start /home/kali/Downloads/Applications/juice-shop_10.3.2
> node app

info: All dependencies in ./package.json are satisfied (OK)
(node:1703) UnhandledPromiseRejectionWarning: Error: /home/kali/Downloads/Applications/juice-shop_10.3.2/node_modules/libxmljs2/build/Release/xmljs.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/home/kali/Downloads/Applications/juice-shop_10.3.2/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/kali/Downloads/Applications/juice-shop_10.3.2/node_modules/libxmljs2/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kali/Downloads/Applications/juice-shop_10.3.2/node_modules/libxmljs2/index.js:4:16)
(node:1703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bkimminich** [comment]
Please make sure you have the right archive downloaded for your OS and Node.js version. Otherwise some precompiled binaries won't work. Also make sure your Node.js installation is up to date, on Linux that's sometimes a problem when you install via package managers. If all else fails, you might want to try installation from source or Docker instead.

**Comment by bkimminich** [comment]
Further questions please to https://gitter.im/bkimminich/juice-shop
