### ISSUE TITLE
[🐛] Unable to launch the application

### ISSUE THREAD

**Issue by thecompilerctf** [juice-shop/juice-shop#1398]
# :bug: Bug report

## Description

npm start fails after npm install. 
info: All dependencies in ./package.json are satisfied (OK)

## :fire: Exception or Error

<pre><code>
(node:6766) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile '/root/Desktop/Projects/juice-shop/data/static/JuiceShopJingle.vtt' -> '/root/Desktop/Projects/juice-shop/frontend/dist/frontend/assets/public/videos/JuiceShopJingle.vtt'
    at Object.copyFileSync (fs.js:1912:3)
    at restoreOverwrittenFilesWithOriginals (/root/Desktop/Projects/juice-shop/lib/startup/restoreOverwrittenFilesWithOriginals.js:13:6)
    at Object.<anonymous> (/root/Desktop/Projects/juice-shop/server.js:97:62)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at /root/Desktop/Projects/juice-shop/app.js:7:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

</code></pre>

## :deciduous_tree: Your Environment
Node Version : v14.4.0
Npm Version : 6.14.5
OS : Kali Linux 2020.2

**Comment by bkimminich** [comment]
Most likely your preceding `npm install` ran into folder write permission errors already. If you downloaded a ZIP archive you might still miss permissions on your folder to copy some files around. See https://pwning.owasp-juice.shop/appendix/troubleshooting.html and and https://github.com/bkimminich/juice-shop/issues/868.
