### ISSUE TITLE
Server crash during SQL injection

### ISSUE THREAD

**Issue by thoastbrot** [juice-shop/juice-shop#155]
Hi,

I just crashed the app. I'm trying not to spoil myself and haven't read most of it - I union'ed sqlite_master. I added the traceback I found to the npm.log.

[npm-debug.txt](https://github.com/bkimminich/juice-shop/files/126975/npm-debug.txt)

**Comment by bkimminich** [comment]
Your log doesn't really spoil any challenges, so I'll re-post it here:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node-v4.3.0-linux-x64/bin/node',
1 verbose cli   '/opt/node-v4.3.0-linux-x64/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart juice-shop@1.24.1
6 info start juice-shop@1.24.1
7 verbose unsafe-perm in lifecycle true
8 info juice-shop@1.24.1 Failed to exec start script
9 verbose stack Error: juice-shop@1.24.1 start: `node app`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/node-v4.3.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/opt/node-v4.3.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid juice-shop@1.24.1
11 verbose cwd /home/saftladen/juice-shop
12 error Linux 3.16.0-4-amd64
13 error argv "/opt/node-v4.3.0-linux-x64/bin/node" "/opt/node-v4.3.0-linux-x64/bin/npm" "start"
14 error node v4.3.0
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error juice-shop@1.24.1 start: `node app`
17 error Exit status 1
18 error Failed at the juice-shop@1.24.1 start script 'node app'.
18 error This is most likely a problem with the juice-shop package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app
18 error You can get their info via:
18 error     npm owner ls juice-shop
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

To be honest, this error doesn't tell anything about what happened during the crash. Did the app crash during subsequent `npm start`calls after you did this SQLI UNION?

If you can reproduce this (or a similar) crash with the latest version, please post the SQLI string you used along with the crash log.

**Comment by bkimminich** [comment]
Maybe try  https://github.com/rook2pawn/node-ddos to prevent death from request overload...?
