### ISSUE TITLE
Calling /rest/order-history without the JWT crashes Juice Shop [🐛] 

### ISSUE THREAD

**Issue by Konachan** [juice-shop/juice-shop#1628]
# :bug: Bug report

## Description

After calling /rest/order-history without the `Authorization` header causes Juice Shop to throw an error and exit completely.

### Is this a regression?

Unknown

## :microscope: Minimal Reproduction

Call:
<pre><code>
GET /rest/order-history HTTP/1.1
Host: <juiceshop>:3000
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Referer: http://<juiceshop>:3000/
Accept-Encoding: gzip, deflate
Connection: close
</code></pre>

Note: I removed some other Headers but the one causing the error is `Authorization`. Tested by removing them one by one.

## :fire: Exception or Error

<pre><code>
TypeError: Cannot read property 'replace' of undefined
    at /home/kona/Schreibtisch/juice-shop_12.7.1/build/routes/orderHistory.js:12:88
    at Layer.handle [as handle_request] (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/layer.js:95:5)
    at /home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:275:10)
    at /home/kona/Schreibtisch/juice-shop_12.7.1/build/routes/verify.js:133:5
    at Layer.handle [as handle_request] (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:317:13)
    at /home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:275:10)
    at /home/kona/Schreibtisch/juice-shop_12.7.1/build/routes/verify.js:69:5
    at Layer.handle [as handle_request] (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:317:13)
    at /home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/index.js:275:10)
    at logger (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/kona/Schreibtisch/juice-shop_12.7.1/node_modules/express/lib/router/layer.js:95:5)

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

v15.14.0
7.9.0
</code></pre>

### Additional Information

-

**Comment by bkimminich** [comment]
💥 Ouch... Good catch! 👍
