### ISSUE TITLE
JuiceShop docker container crashes when scanning[🐛] 

### ISSUE THREAD

**Issue by vbisbest** [juice-shop/juice-shop#1754]
Using JS 13.1 and 13.2, the docker container crashes when scanning with an automated DAST scanner.  Unfortunaley I dont know which requests are causing the issue.   Here is the log output just before it crashes:

```
info: Solved 6-star continueCodeChallenge (Imaginary Challenge)
info: Cheat score for continueCodeChallenge solved in 0min (expected ~12min) with hints allowed: 0.9923152777777777

/juice-shop/build/routes/updateProductReviews.js:20

            utils.solveIf(challenges.forgedReviewChallenge, () => { return (user === null || user === void 0 ? void 0 : user.data) && result.original[0].author !== user.data.email && result.modified === 1; }); // vuln-code-snippet hide-line                                                                                                                                                       ^
TypeError: Cannot read properties of undefined (reading 'author')
    at /juice-shop/build/routes/updateProductReviews.js:20:154
    at Object.exports.solveIf (/juice-shop/build/lib/utils.js:107:38)
    at /juice-shop/build/routes/updateProductReviews.js:20:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.4.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.4.0>
npm notice Run `npm install -g npm@8.4.0` to update!
npm notice 
```

**Comment by vbisbest** [comment]
It seems to be this request that causes JS to crash.

```
PUT http://localhost:3000/rest/products/1/reviews HTTP/1.1
Host: localhost:3000
User-Agent: frisby/2.1.3 (+https://github.com/vlucas/frisby)
Content-Length: 44
Accept: */*
Cache-Control: no-cache
Connection: close
Content-Type: application/json
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MjEsInVzZXJuYW1lIjoiIiwiZW1haWwiOiJmb29vb28xQGJhci5jb20iLCJwYXNzd29yZCI6ImUxMGFkYzM5NDliYTU5YWJiZTU2ZTA1N2YyMGY4ODNlIiwicm9sZSI6ImN1c3RvbWVyIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0LnN2ZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0wMS0yOCAxNjoxODoxNi4xNDAgKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyMi0wMS0yOCAxNjoxODoxNi4xNDAgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiaWF0IjoxNjQzMzg2NzIzLCJleHAiOjE2NDM0MDQ3MjN9.PQIswXcOQ3aXcQfspiSPyR_XlsAThuQt5AscsWLmTQSiPXbBlFgaeACryy2YzX6WDx8_lsm244sF0i03PiVDog6dJTeF4L2Iz0KcXpSLLZYrld9XiRXE7vAMa33XlUMYptnOknoHGwSx4cNGhAugTNekbfrqPzixoyFMYJGCI0c; continueCode=e1ZwBLrKqWXamDEzyO9RgGmMT6CrfyUMHpWc44Go2M36xjVQbJvklN87pPY4
Accept-Encoding: gzip

{"message":"798482723","author":"Anonymous"}
```

**Comment by bkimminich** [comment]
Seems that the access to `result.original[0].author` failed because `result.original[0]` was `undefined`. I will add a safety check there so it at least doesn't crash.

**Comment by bkimminich** [comment]
When https://github.com/juice-shop/juice-shop/actions/runs/1768786692 is finished feel free to test if the problem is gone with the `snapshot` Docker image containing Juice Shop `v13.3.0-SNAPSHOT` or later.
