### ISSUE TITLE
[🐛] docker build crashes due to @fortawesome version update 5.14.0 -> 6.0.0

### ISSUE THREAD

**Issue by jbhong** [juice-shop/juice-shop#1759]
@fortawesome recently updated (now 6.0.0), and is causing issues when building via docker (I suppose it would be the same in other installation methods as well).
e.g., in ./frontend/src/app/about/about.component.ts line 17 throws an error of type mismatch.

A quick bypass is to use the previous versions by editing the ./frontend/package.json file and forcing it to install the noted versions (i.e., remove '^'):

    "@fortawesome/fontawesome-svg-core": "1.2.30",
    "@fortawesome/free-brands-svg-icons": "5.14.0",
    "@fortawesome/free-regular-svg-icons": "5.14.0",
    "@fortawesome/free-solid-svg-icons": "5.14.0",

On a side note (minor), this version of iltorb is no longer accessible:
...
http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz
...

**Comment by PeterMosmans** [comment]
Wouldn't a nicer solution be that the `package-lock.json` file would be committed to the repo as well? So that we can create reproducible builds ?
Currently it's explicitly 'removed' from the repository, as it's mentioned in the `.gitignore` file.

**Comment by bkimminich** [comment]
Having the `package-lock.json` committed caused some other problems back in the day, I just cannot recall exactly which. But they were more annoying than the occasional build breaking from a changed dependency. If someone wants to revisit that decision, please feel free to do so! 👍 

The issue with FontAwesome is already fixed, so installations from source are already fine. Release of `v13.2.2` and corresponding Docker images is currently ongoing as well.

**Comment by jbhong** [comment]
Thanks, it builds fine with docker now. But when I run it, I get errors below. Any ideas what might cause them?

```
> juice-shop@13.2.2 start /juice-shop
> node build/app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v14.19.0 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Configuration default validated (OK)
(node:18) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile 'data/static/botDefaultTrainingData.json' -> 'data/chatbot/botDefaultTrainingData.json'
    at Object.copyFileSync (fs.js:2061:3)
    at initialize (/juice-shop/build/routes/chatbot.js:25:8)
    at Object.<anonymous> (/juice-shop/build/routes/chatbot.js:33:6)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/juice-shop/build/server.js:98:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /juice-shop/build/app.js:7:20
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: Required file server.js is present (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main.js is present (OK)
info: Required file tutorial.js is present (OK)
info: Required file polyfills.js is present (OK)
info: Required file runtime.js is present (OK)
info: Required file vendor.js is present (OK)
[Error: EACCES: permission denied, copyfile '/juice-shop/data/static/legal.md' -> '/juice-shop/ftp/legal.md'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'copyfile',
  path: '/juice-shop/data/static/legal.md',
  dest: '/juice-shop/ftp/legal.md'
}
(node:18) UnhandledPromiseRejectionWarning: SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:78:34)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
info: Port 3000 is available (OK)
```

**Comment by bkimminich** [comment]
That doesn't happen when I'm running Juice Shop in a Docker container, so I assume it's unrelated to the application.

**Comment by jbhong** [comment]
Could it be that because I am using node:14? I am building a multi architecture image and so was using node:14 for both amd and arm builds.

**Comment by jbhong** [comment]
Okay so even a fresh build fails on me.

My build code:

`docker buildx build --platform linux/amd64 -t myaccount/juiceimage:juicetag -f ./Dockerfile --push .`

This is so that later I could add linux/arm64 using node:14 but might build them separately.


Anyway, it builds fine but when I run it:

```
PS G:\juice-shop-master> docker run -p 3000:3000 -it myaccount/juiceimage:juicetag

> juice-shop@13.2.2 start
> node build/app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v16.13.2 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Configuration default validated (OK)
node:fs:2800
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, copyfile 'data/static/botDefaultTrainingData.json' -> 'data/chatbot/botDefaultTrainingData.json'
    at Object.copyFileSync (node:fs:2800:3)
    at initialize (/juice-shop/build/routes/chatbot.js:25:8)
    at Object.<anonymous> (/juice-shop/build/routes/chatbot.js:33:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/juice-shop/build/server.js:98:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /juice-shop/build/app.js:7:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: 'data/static/botDefaultTrainingData.json',
  dest: 'data/chatbot/botDefaultTrainingData.json'
}
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.4.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.4.1
npm notice Run npm install -g npm@8.4.1 to update!
npm notice
```

I'm running docker desktop 4.4.4 on Windows.

**Comment by bkimminich** [comment]
Sorry, I can't give custom Docker build support. Too many variables unrelated to Juice Shop that can cause all kinds of issues.

**Comment by jbhong** [comment]
Alright, thanks anyway
