### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by divi7777777** [juice-shop/juice-shop#1800]
i built a dockerfile of your given dockerfile then try to host but getting this error,how can i resolve this

/juice-shop/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
              ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/juice-shop/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
    at new Sequelize (/juice-shop/node_modules/sequelize/lib/sequelize.js:340:20)
    at Object.<anonymous> (/juice-shop/build/models/index.js:12:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

**Comment by bkimminich** [comment]
Our `Dockerfile` works just fine, I just tried `docker run --rm -p 3000:3000 bkimminich/juice-shop:snapshot`. So whatever goes wrong for you, can't be related to our `Dockerfile`. Errors in custom images are not in scope for support here, especially when the custom Dockerfile is unknown.

**Comment by bkimminich** [comment]
Our Docker image build process for reference can be found here: https://github.com/juice-shop/juice-shop/blob/master/.github/workflows/ci.yml#L253-L301

**Comment by bkimminich** [comment]
🐸 Also, you might want to change your JFrog password... 😉
