### ISSUE TITLE
[🐛] Better handle [mongodb-js-native-legacy] simulation command besides sleep(x) command 

### ISSUE THREAD

**Issue by italle** [juice-shop/juice-shop#1836]
# :bug: Bug report

## Description

Since that juice-shop wants to explore the hacker with js-native-legacy for mangoDB via sleep command, when the hacker get this hint, he might try the other type of legcy command fx version(), ls() .

### Is this a regression?

I do not know. I am the fresh new user to play around JS

## :microscope: Minimal Reproduction

http://localhost:3000/rest/products/[mongodb-js-native-legacy]/reviews
using one of command from https://www.mongodb.com/docs/manual/reference/method/js-native-legacy/

## :fire: Exception or Error

<pre><code>

undefined:3
return this.product == version()
            ^

ReferenceError: version is not defined
    at Object.eval (eval at $where (/home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/dist/DocumentMatcher.js:419:23), <anonymous>:3:13)
    at DocumentMatcher._docMatcher (/home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/dist/DocumentMatcher.js:424:38)
    at DocumentMatcher.documentMatches (/home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/dist/DocumentMatcher.js:112:19)
    at queryFilter (/home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/dist/Cursor.js:243:39)
    at EventEmitter.<anonymous> (/home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/dist/DocumentRetriver.js:114:42)
    at EventEmitter.emit (/home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/node_modules/eventemitter3/index.js:89:35)
    at /home/cuckoo/juice-shop/juice-shop/node_modules/marsdb/dist/StorageManager.js:122:19

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

**Comment by bkimminich** [comment]
Juice Shop does not prescribe to use the `sleep()` command for this challenge. As long as you are _somehow_ able to delay the response of the query by 2 seconds, the challenge will be solved successfully: https://github.com/juice-shop/juice-shop/blob/master/routes/showProductReviews.ts#L35 - The `sleep()` function just seems like the easiest way to achieve this.

**Comment by italle** [comment]
Thanks for the hint,  the user can use this kind of link without hitting exception.
http://localhost:3000/rest/products/function(){var net=1;return ++net}()/reviews
