### ISSUE TITLE
[🐛] Docker container for arm64 fails for V.14.1.0 and v14.1.1

### ISSUE THREAD

**Issue by andifalk** [juice-shop/juice-shop#1850]
# :bug: Bug report

## Description

Running a docker container using the arm64 images for V.14.1.0 and v14.1.1 fails with the following error message:

>  info: All dependencies in ./package.json are satisfied (OK)
> (node:18) UnhandledPromiseRejectionWarning: Error: Please install sqlite3 package manually

### Is this a regression?

Yes, the previous version in which this bug was not present was: `v.14.0.1`

## :microscope: Minimal Reproduction

Just run docker run --rm -p 3000:3000 bkimminich/juice-shop:v14.1.1-arm

## :fire: Exception or Error

<pre><code>

> juice-shop@14.1.1 start /juice-shop
> node build/app

info: All dependencies in ./package.json are satisfied (OK)
(node:18) UnhandledPromiseRejectionWarning: Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/juice-shop/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55:15)
    at new ConnectionManager (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:18:21)
    at new SqliteDialect (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/index.js:13:30)
    at new Sequelize (/juice-shop/node_modules/sequelize/lib/sequelize.js:190:20)
    at Object.<anonymous> (/juice-shop/build/models/index.js:30:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

Docker version 20.10.17 on MacOS 12.5 (Apple M1 Pro)

</code></pre>

**Comment by bkimminich** [comment]
Could you try the regular tag w/o ˋ-armˋ suffix? For 64Bit that is recommended, the other was kept for legacy reasons only, but if it no longer works I’ll of course stop building it.

**Comment by andifalk** [comment]
Yes, v14.1.0 and v14.1.1 are also working fine without the `arm` suffix. I have used the suffix because some older versions of the juice shop did not work in the past when not adding this.  
So if these `legacy`images do not work anymore it would be better to stop providing these.
So, issue can be closed from my side.
