### ISSUE TITLE
[🐛] Visiting /api/Deliverys address crashes the container/app

### ISSUE THREAD

**Issue by viorelstroe** [juice-shop/juice-shop#1928]
# :bug: Bug report

## Description

Create the server fresh and after the visit with browser to http://localhost:3000/api/Deliverys
Server collapse/shutdown, if docker container disappear 

### Is this a regression?

Yes, the previous version in which this bug was not present was: `x.y.z`

## :microscope: Minimal Reproduction
Reproduced with:
Docker following: https://github.com/juice-shop/juice-shop#docker-container
Windows10 following: https://github.com/juice-shop/juice-shop#packaged-distributions

1. Start the server
2. Navigate to http://localhost:3000/api/Deliverys with any browser

## :fire: Exception or Error
<pre><code>
docker logs -t -f 9c5088ad9c2b7cddf20245f29bdf78d84d48830a293836c57de72f2da89dcdb4
2022-11-28T18:15:05.252070025Z info: All dependencies in ./package.json are satisfied (OK)
2022-11-28T18:15:06.227430984Z info: Chatbot training data botDefaultTrainingData.json validated (OK)
2022-11-28T18:15:06.273231420Z info: Detected Node.js version v16.18.1 (OK)
2022-11-28T18:15:06.273268679Z info: Detected OS linux (OK)
2022-11-28T18:15:06.273310856Z info: Detected CPU x64 (OK)
2022-11-28T18:15:06.298750023Z info: Configuration default validated (OK)
2022-11-28T18:15:06.303864941Z info: Entity models 19 of 19 are initialized (OK)
2022-11-28T18:15:06.338940666Z info: Required file server.js is present (OK)
2022-11-28T18:15:06.338984489Z info: Required file styles.css is present (OK)
2022-11-28T18:15:06.339284200Z info: Required file main.js is present (OK)
2022-11-28T18:15:06.339292956Z info: Required file index.html is present (OK)
2022-11-28T18:15:06.339490837Z info: Required file tutorial.js is present (OK)
2022-11-28T18:15:06.339668380Z info: Required file polyfills.js is present (OK)
2022-11-28T18:15:06.339821445Z info: Required file runtime.js is present (OK)
2022-11-28T18:15:06.340135400Z info: Required file vendor.js is present (OK)
2022-11-28T18:15:06.345239685Z info: Port 3000 is available (OK)
2022-11-28T18:15:07.697434442Z info: Server listening on port 3000
2022-11-28T18:15:22.931918972Z /juice-shop/node_modules/jws/index.js:78
2022-11-28T18:15:22.931959078Z   return jwsSig.split('.')[2];
2022-11-28T18:15:22.931963474Z                 ^
2022-11-28T18:15:22.931965426Z
2022-11-28T18:15:22.931967251Z TypeError: Cannot read properties of undefined (reading 'split')
2022-11-28T18:15:22.931969473Z     at signatureFromJWS (/juice-shop/node_modules/jws/index.js:78:17)
2022-11-28T18:15:22.931972059Z     at Object.jwsVerify [as verify] (/juice-shop/node_modules/jws/index.js:97:21)
2022-11-28T18:15:22.931973954Z     at verify (/juice-shop/build/lib/insecurity.js:32:31)
2022-11-28T18:15:22.931975677Z     at Object.exports.isDeluxe (/juice-shop/build/lib/insecurity.js:142:26)
2022-11-28T18:15:22.931977408Z     at /juice-shop/build/routes/delivery.js:18:37
</code></pre>

## :deciduous_tree: Your Environment
<pre><code>
v16.15.0
8.5.5
</code></pre>

**Comment by bkimminich** [comment]
Will be fixed with the next regular release. Thanks for reporting this 🐛!
