### ISSUE TITLE
[🐛] Unsigned JWT challenge is not being accepted

### ISSUE THREAD

**Issue by bekh6ex** [juice-shop/juice-shop#2009]
# :bug: Bug report

## Description
**Challenge**:  Unsigned JWT (Forge an essentially unsigned JWT token that impersonates the (non-existing) user jwtn3d@juice-sh.op.)

When I decode valid JWT created by the Juice Shop I get following payload:
```json
{"status":"success","data":{"id":3,"username":"","email":"bender@juice-sh.op","password":"0c36e517e3fa95aabf1bbffc6744a4ef","role":"customer","deluxeToken":"","lastLoginIp":"","profileImage":"assets/public/images/uploads/default.svg","totpSecret":"","isActive":true,"createdAt":"2023-05-09 15:58:35.346 +00:00","updatedAt":"2023-05-09 15:58:35.346 +00:00","deletedAt":null},"iat":1683649393,"exp":1683667393}
```

If I adjust `email` field in this payload (header and signature are changed accordingly), I get 401 responses and challenge is not accepted.

But if I also rename top level `data` field into `payload` (as written in the solution), it is magically accepted.

Juice Shop Version: 9a0789b5ecb4ee76fe528b1860095e945f6302ac

### Is this a regression?

I don't know

## :microscope: Minimal Reproduction

- Login as any user
- Grab generated JWT 
- Change JWT header to `{"typ":"JWT","alg":"none"}`
- Change JWT payload property `/data/email` to `jwtn3d@juice-sh.op`
- Base64url encode both parts and concatenate them together with `.`, also adding `.` to the end
- Use new token in `Authorization` header like `Authorization: Bearer <token>`
- Observe 401 error and absence of challenge acceptance 

## :fire: Exception or Error

<pre><code>
TypeError: Cannot read properties of undefined (reading 'id')
    at Object.put (/.../juice-shop/build/lib/insecurity.js:54:30)
    at /.../juice-shop/build/lib/insecurity.js:167:40
    at module.exports.verify (/.../juice-shop/node_modules/jsonwebtoken/index.js:65:3)
    at /.../juice-shop/build/lib/insecurity.js:164:13
    at Layer.handle [as handle_request] (/.../juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at next (/.../juice-shop/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/.../juice-shop/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/.../juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at /.../juice-shop/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/.../juice-shop/node_modules/express/lib/router/index.js:346:12)
    at next (/.../juice-shop/node_modules/express/lib/router/index.js:280:10)
    at /.../juice-shop/build/routes/verify.js:135:5
    at Layer.handle [as handle_request] (/.../juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../juice-shop/node_modules/express/lib/router/index.js:328:13)
    at /.../juice-shop/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/.../juice-shop/node_modules/express/lib/router/index.js:346:12)
    at next (/.../juice-shop/node_modules/express/lib/router/index.js:280:10)
    at /.../juice-shop/build/routes/verify.js:71:5
    at Layer.handle [as handle_request] (/.../juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../juice-shop/node_modules/express/lib/router/index.js:328:13)
    at /.../juice-shop/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/.../juice-shop/node_modules/express/lib/router/index.js:346:12)
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
➜ node -v && npm -v
v19.8.1
9.6.4
</code></pre>

**Comment by bekh6ex** [comment]
Wait. Let me double-check.

**Comment by bekh6ex** [comment]
My apologies. Could not confirm. Closing
