### ISSUE TITLE
[🐛] Could not locate bindings file xmljs.node

### ISSUE THREAD

**Issue by chkoelbl** [juice-shop/juice-shop#2228]
# :bug: Bug report

## Description

Starting JuiceShop after installing does not find bindings file xmljs.node

npm install (with logs) does not show any problems. But when trying to start the application with "npm start" I got an exception.

I also tried:
- npm rebuild
- removing node_modules and updating `npm by npm install -g npm@latest`
- Same results with Node.js v18.20.0

### Is this a regression?

Yes, the previous version in which this bug was not present was JuiceShop@15.0.0 with npm 10.5.0 and Node 18.20.0. 

And JuiceShop@16.0.0 with Node v20.12.0 and NPM 10.5.0 works on my Ubuntu VM without problems.

## :microscope: Minimal Reproduction

1. Download Prebuilt Binaries Node v20.12.0 from https://nodejs.org/en/download/prebuilt-binaries/current. 
2. Extract to 'myfolder'
3. 4. Add 'myfolder/node20...' to PATH
4. Go back to 'myfolder' and create standalone python as described here: https://plainenglish.io/blog/install-python-on-a-locked-down-pc-without-local-admin-37a440c42c12
5. Go back to 'myfolder' and clone JuiceShop
6. cd to JuiceShop
7. npm install
8. npm start

## :fire: Exception or Error

<pre><code>

C:\Users\me\Tools\schulung\juice-shop>npm start

> juice-shop@16.0.0 start
> node build/app

WARNING: NODE_ENV value of 'kvb' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
info: All dependencies in ./package.json are satisfied (OK)
C:\Users\me\Tools\schulung\juice-shop\node_modules\bindings\bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\build\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\build\Debug\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\build\Release\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\out\Debug\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\Debug\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\out\Release\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\Release\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\build\default\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\compiled\20.12.0\win32\x64\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\addon-build\release\install-root\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\addon-build\debug\install-root\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\addon-build\default\install-root\xmljs.node
 → C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\lib\binding\node-v115-win32-x64\xmljs.node
    at bindings (C:\Users\me\Tools\schulung\juice-shop\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\lib\bindings.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\me\Tools\schulung\juice-shop\node_modules\libxmljs2\index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\me\Tools\schulung\juice-shop\build\routes\fileUpload.js:39:16) {
  tries: [
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\build\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\build\\Debug\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\build\\Release\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\out\\Debug\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\Debug\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\out\\Release\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\Release\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\build\\default\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\compiled\\20.12.0\\win32\\x64\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\addon-build\\release\\install-root\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\addon-build\\debug\\install-root\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\addon-build\\default\\install-root\\xmljs.node',
    'C:\\Users\\me\\Tools\\schulung\\juice-shop\\node_modules\\libxmljs2\\lib\\binding\\node-v115-win32-x64\\xmljs.node'
  ]
}

Node.js v20.12.0

</code></pre>

## :deciduous_tree: Your Environment

Got the same error using JuiceShop@16.0.0 with Node.js v20.12.0 or v18.20.0 and npm 10.5.0

I'm using Node's Windows x64 Prebuild Binaries without installation (https://nodejs.org/en/download/prebuilt-binaries/current).

<pre><code>
v20.12.0
10.5.0
python 3.12.2
</code></pre>

### Additional Information

Log file from `npm start`

```
0 verbose cli C:\Users\me\Tools\schulung\node20\node.exe C:\Users\me\Tools\schulung\node20\node_modules\npm\bin\npm-cli.js
1 info using npm@10.5.0
2 info using node@v20.12.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\me\Tools\schulung\node20\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\me\Tools\schulung\juice-shop\.npmrc Completed in 1ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\me\Tools\schulung\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\me\Tools\schulung\node20\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 11ms
17 timing npm:load:configload Completed in 11ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm start
22 verbose argv "start"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:C:\Users\me\AppData\Local\npm-cache\_logs\2024-04-02T17_41_24_362Z-
26 verbose logfile C:\Users\me\AppData\Local\npm-cache\_logs\2024-04-02T17_41_24_362Z-debug-0.log
27 timing npm:load:logFile Completed in 9ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 46ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing command:run-script Completed in 1608ms
34 timing command:start Completed in 1621ms
35 verbose exit 1
36 timing npm Completed in 1745ms
37 verbose code 1
```

**Comment by chkoelbl** [comment]
I figured out, that the issue is caused by missing windows-build-utils resp. not using admin privileges during installation. Since I want to avoid admin privs I solved the problem by using prebuild packages. Thank you very much for providing those! They are very helpfull!
