### ISSUE TITLE
juice-shop-x.yy.z_node6_windows_x64 missing files

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#223]
```
$ npm start

> juice-shop@2.16.0 start D:\Downloads\juice-shop-2.16.0_node6_windows_x64
> node app

module.js:457
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Downloads\juice-shop-2.16.0_node6_windows_x64\node_modules\glob\glob.js:44:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! juice-shop@2.16.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juice-shop@2.16.0 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the juice-shop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs juice-shop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls juice-shop
npm ERR! There is likely additional logging output above.
```

**Comment by bkimminich** [comment]
## Facts
- The current _Windows_ v4 archive is ~43 MB and the v6 only ~29 MB
- The current _Linux_ v4 archive is ~36 MB vs. 27 MB for v6
- `npm install` from scratch works for both v4 and v6, as does subsequent `start` or `test`
- On Heroku (using v5 😕 no matter if v4 or v6 is deployed) the application works

## Assumption

This cannot be a problem happening during build or launch. It must happen during `grunt package`

## TODO
- [x] compare ZIP contents for Windows (might get tricky due to [overlong-path problem](https://github.com/nodejs/node-v0.x-archive/issues/6960)!)
- [x] compare ZIP contents for Linux

**Comment by bkimminich** [comment]
In v6 all sub-dependencies are in the top-level `node_modules` while in v4 they are nested. During `grunt package` currently the files are selected assuming the nested approach:

```
            src: [
              '*.md',
              'app.js',
              'server.js',
              'package.json',
              'app/index.html',
              'app/bower_components/**',
              'app/css/*.css',
              'app/css/geo-bootstrap/**',
              'app/dist/juice-shop.min.js',
              'app/i18n/*.json',
              'app/private/**',
              'app/public/**',
              'data/*.js',
              'ftp/**',
              'lib/*.js',
              'models/*.js',
              'routes/*.js',
              'node_modules/body-parser/**',
              'node_modules/colors/**',
              'node_modules/cookie-parser/**',
              'node_modules/cors/**',
              'node_modules/errorhandler/**',
              'node_modules/express/**',
              'node_modules/express-jwt/**',
              'node_modules/glob/**',
              'node_modules/hashids/**',
              'node_modules/helmet/**',
              'node_modules/jsonwebtoken/**',
              'node_modules/morgan/**',
              'node_modules/multer/**',
              'node_modules/pdfkit/**',
              'node_modules/sanitize-html/**',
              'node_modules/sequelize/**',
              'node_modules/sequelize-restful/**',
              'node_modules/serve-favicon/**',
              'node_modules/serve-index/**',
              'node_modules/socket.io/**',
              'node_modules/sqlite3/**',
              'node_modules/z85/**'
            ]
```

Changing into `node_modules/**` should solve this, but with the downside of having all dev dependencies also in the ZIP.
