### ISSUE TITLE
Failed at the juice-shop@4.0.0 start script 'node app'.

### ISSUE THREAD

**Issue by r00tb3** [juice-shop/juice-shop#351]
When I hit `npm start` I get the following error :--
```
> juice-shop@4.0.0 start /home/r00tb3/juice-shop
> node app

module.js:328
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/r00tb3/juice-shop/node_modules/readable-stream/lib/_stream_readable.js:6:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! juice-shop@4.0.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juice-shop@4.0.0 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the juice-shop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs juice-shop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls juice-shop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/r00tb3/juice-shop/npm-debug.log


```

What's the solution for this?

**Comment by bkimminich** [comment]
Seems you miss some library. Did your `npm install` run through without error?

**Comment by r00tb3** [comment]
Yes. I've reinstalled everything twice but it doesn't seem to work.

**Comment by bkimminich** [comment]
I installed your exact node version (`4.2.6`) on my Windows 10 machine, deleted `node_modules` and `app/bower_components` and ran `npm install`.

It took a while, but ran through only with warnings, no errors. Subsequent `npm start` worked just fine.

So, I'm pretty sure it's something with your combination of Linux & Node. Did you try [the pre-packaged `TGZ` for your version of node](https://github.com/bkimminich/juice-shop/releases/download/v4.0.0/juice-shop-4.0.0_node4_linux_x64.tgz)?

**Comment by r00tb3** [comment]
It worked installed the version 4.0.0 as you recommended thanks...
