### ISSUE TITLE
Unable to start juice-shop with master

### ISSUE THREAD

**Issue by Contrast-AlexB** [juice-shop/juice-shop#496]
Hi, with the most recent updates to master I'm unable to start the app with node 6 or node 8, any suggestions ?

```
$ npm start

> juice-shop@7.0.0 start /Users/ab/juice-shop
> node app

/Users/ab/juice-shop/server.js:262
    models.sequelize.sync({ force: true }).then(async function () {
                                                ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ab/juice-shop/app.js:1:78)
```

**Comment by bkimminich** [comment]
Node 6.x support was dropped with Juice Shop 7.0.0 mostly so we could start using `async` and `await` of Node 7.x and later. So I cannot imagine that you get the same error when using a Node 8.x installation. Please check if some other error occurs on Node 8.x or if maybe switching the version did not work? Are you using `nvm` or two different manual installations?

**Comment by Contrast-AlexB** [comment]
I was using nvm, but when I switched versions I didn't rebuild the npm modules. Node 8 is working fine. Thank you for your help & info!
