### ISSUE TITLE
docker run --rm -p 3000:3000 bkimminich/juice-shop failed to start.

### ISSUE THREAD

**Issue by slevi2103** [juice-shop/juice-shop#554]
2018-05-13T11:35:36.709Z '[FileStreamRotator] Failed to store log audit at:' './.audit.json' 'Error:' { Error: EROFS: read-only file system, open './.audit.json'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.writeFileSync (fs.js:1319:33)
    at Object.FileStreamRotator.writeAuditLog (/juice-shop/node_modules/file-stream-rotator/FileStreamRotator.js:241:12)
    at Object.FileStreamRotator.addLogToAudit (/juice-shop/node_modules/file-stream-rotator/FileStreamRotator.js:305:27)
    at EventEmitter.<anonymous> (/juice-shop/node_modules/file-stream-rotator/FileStreamRotator.js:408:34)
    at EventEmitter.emit (events.js:180:13)
    at /juice-shop/node_modules/file-stream-rotator/FileStreamRotator.js:448:20
    at process._tickCallback (internal/process/next_tick.js:176:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: './.audit.json' }
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: EROFS: read-only file system, open './access.log.2018-05-13'
Emitted 'error' event at:
    at WriteStream.<anonymous> (/juice-shop/node_modules/file-stream-rotator/FileStreamRotator.js:503:15)
    at WriteStream.emit (events.js:180:13)
    at fs.open (fs.js:2225:12)
    at FSReqWrap.oncomplete (fs.js:153:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! juice-shop@7.1.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juice-shop@7.1.0 start script.

**Comment by bkimminich** [comment]
I just downloaded the `latest` Docker image and it starts up fine for me. Could please try and restart or delete and reinstall the image?

**Comment by bkimminich** [comment]
Also please make sure you use the latest Docker version. Running into `read-only file system`-errors like this seems to happen in some older versions. Juice Shop requires a writable file-system, not only for logging but for its general functionality too.

**Comment by slevi2103** [comment]
I did what you mention and also tried to run it with sudo.
Still doesn't work.
I also upgrade NPM and nothing.

I used to run it on the same environment.

**Comment by bkimminich** [comment]
You updated NPM inside the Docker image? Doing it outside would not make a difference, and doing it inside might mess things up. My recommendation is to remove the image completely, then update your Docker installation, then get the `latest` image again.

**Comment by slevi2103** [comment]
OK I shutdown Docker and start it again.
The shop is open ;).
