### ISSUE TITLE
Fix Docker build for v1.4.1

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#58]
```
Step 0 : FROM dockerfile/nodejs 
Pulling image (latest) from dockerfile/nodejs, endpoint: https://registry-1.docker.io/v1/ 9a76e1635147
Download complete 511136ea3c5a
Download complete d497ad3926c8
Download complete ccb62158e970
Download complete e791be0477f2
Download complete 3680052c0f5c
Download complete 22093c35d77b
Download complete 5506de2b643b
Download complete b08854b89605
Download complete d0ca2a3c0233
Download complete 1716e82f74f0
Download complete b41d25703535
Download complete e95dbc5735e1
Download complete 5992007b07de
Download complete b4e54ddfb2af
Download complete e05f47abd826
Download complete c368bf6a959f
Download complete 398ff1819212
Download complete 02ef3adc724b
Download complete 101496606a4a
Download complete 9a76e1635147
Download complete 9a76e1635147
Status: Downloaded newer image for dockerfile/nodejs:latest 
---> 9a76e1635147 
Step 1 : MAINTAINER Bjoern Kimminich <docker.com@kimminich.de> 
---> Running in 729b62b6dff1 
---> 43e3cc0fea0d 
Removing intermediate container 729b62b6dff1 
Step 2 : COPY . /juice-shop 
---> 784d90bdea32 
Removing intermediate container 9e2af6d23675 
Step 3 : RUN cd /juice-shop; npm install; node bower_install.js; node grunt_minify.js 
---> Running in b5edd2a9b5f6 
[91mnpm[0m 
[91m [0m 
[91mERR! fetch failed[0m 
[91m https://registry.npmjs.org/express-jwt/-/express-jwt-0.5.0.tgz
[0m 
[91mnpm[0m 
[91m [0m 
[91mERR![0m 
[91m Error: 400 Bad Request
[0m 
[91mnpm ERR![0m 
[91m     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:58:12)
[0m 
[91mnpm [0m 
[91mERR![0m 
[91m     at WriteStream.emit (events.js:117:20)
[0m 
[91mnpm [0m 
[91mERR![0m 
[91m     at evalmachine.<anonymous>:1609:14
npm[0m 
[91m ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
[0m 
[91mnpm ERR![0m 
[91m     at Object.oncomplete (evalmachine.<anonymous>:107:15)
[0m 
[91mnpm ERR![0m 
[91m If you need help, you may report this *entire* log,
[0m 
[91mnpm ERR![0m 
[91m including the npm and node versions, at:
npm [0m 
[91mERR!     <http://github.com/npm/npm/issues>
[0m 
[91m
[0m 
[91mnpm [0m 
[91mERR! [0m 
[91mSystem Linux 3.14.23
[0m 
[91mnpm[0m 
[91m ERR! [0m 
[91mcommand "/usr/local/bin/node" "/usr/local/bin/npm" "install"
[0m 
[91mnpm[0m 
[91m ERR![0m 
[91m [0m 
[91mcwd /juice-shop
[0m 
[91mnpm[0m 
[91m [0m 
[91mERR! [0m 
[91mnode -v[0m 
[91m v0.10.33
[0m 
[91mnpm[0m 
[91m ERR![0m 
[91m [0m 
[91mnpm -v 1.4.28
[0m 
[91mnpm[0m 
[91m ERR! 
[0m 
[91mnpm ERR! Additional logging details can be found in:
npm ERR!     /juice-shop/npm-debug.log
[0m 
[91mnpm ERR![0m 
[91m not ok[0m 
[91m code 0
[0m 
[91m
[0m 
[91mmodule.js:340
[0m 
[91m    throw err;
    [0m 
[91m      ^
[0m 
[91mError: Cannot find module 'bower'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/juice-shop/bower_install.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[0m 
[91m
[0m 
[91mmodule.js:340
[0m 
[91m    throw err;
    [0m 
[91m      ^
[0m 
[91mError: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/juice-shop/grunt_minify.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[0m 
The command [/bin/sh -c cd /juice-shop; npm install; node bower_install.js; node grunt_minify.js] returned a non-zero code: 8
```

**Comment by bkimminich** [comment]
Subsequent build worked fine again. Looks like a one-time glitch.
