### ISSUE TITLE
End-to-end test Docker image

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#605]
1. Spin up container and run e2e-tests manually
2. Automate 1. to happen after image being built on DockerHub (e.g. via WebHook triggering a Travis-CI job)

**Comment by bkimminich** [comment]
First manual result agianst 7.2.3 on `snapshot` image with matching e2e tests from `develop`:

### 4 unsolved challenges
* [x] Security Policy (_now has an e2e test_)
* [x] XXE Tier 1 (see https://github.com/bkimminich/juice-shop/issues/605#issuecomment-396270384)
* [x] XXE Tier 2 (see https://github.com/bkimminich/juice-shop/issues/605#issuecomment-396270384)
* [x] CSRF (see https://github.com/bkimminich/juice-shop/issues/605#issuecomment-396271320)

```
Failures:
1) /#/change-password challenge "csrf" should be able to change password via XSS-powered CSRF-attack on password change without passing current password
  Message:
    Expected 'http://192.168.99.100:32768/#/login' to match /\/search/.

  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\changePasswordSpec.js:37:39)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>

2) /#/change-password challenge "csrf" (shared) challenge 'CSRF' should be solved on score board
  Message:
    Expected 'label label-success ng-hide' not to match 'ng-hide'.
  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\_sharedSpec.js:9:89)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
  Message:

    Expected 'label label-danger label-button' to match 'ng-hide'.
  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\_sharedSpec.js:10:88)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

3) /#/complain challenge "xxeFileDisclosure" (shared) challenge 'XXE Tier 1' should be solved on score board
  Message:
    Expected 'label label-success ng-hide' not to match 'ng-hide'.
  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\_sharedSpec.js:9:89)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
  Message:
    Expected 'label label-danger label-button' to match 'ng-hide'.
  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\_sharedSpec.js:10:88)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

4) /#/complain challenge "xxeDos" (shared) challenge 'XXE Tier 2' should be solved on score board
  Message:
    Expected 'label label-success ng-hide' not to match 'ng-hide'.
  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\_sharedSpec.js:9:89)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
  Message:
    Expected 'label label-danger label-button' to match 'ng-hide'.

  Stack:
    Error: Failed expectation
        at UserContext.it (C:\Data\GitHub\juice-shop\test\e2e\_sharedSpec.js:10:88)
        at C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Data\GitHub\juice-shop\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Data\GitHub\juice-shop\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

141 specs, 4 failures
Finished in 246.273 seconds
```

**Comment by bkimminich** [comment]
Verified that exact same challenges remain unsolved on `lastest` image from `master` branch, so it seems independent of changing the user permissions via #603.

**Comment by bkimminich** [comment]
Unsolved XXE Tier 1+2 challenge are caused by a conditional check in `complainSpec.js` where different attacks & results are expected for Windows and Linux machines. This condition assumes that the tests are executed _on the same machine_ as the server under test. When testing a Docker instance (Alpine Linux) by running the e2e suite on Windows, the wrong attacks and checks are done with **cannot** solve those challenges.

**Comment by bkimminich** [comment]
CSRF challenge cannot be solved by test suite because it has `localhost:3000` hardcoded which is not the correct URL for a running Docker container under test:

```
browser.get('/#/search?q=%3Cscript%3Exmlhttp%20%3D%20new%20XMLHttpRequest;%20xmlhttp.open(\'GET\',%20\'http:%2F%2Flocalhost:3000%2Frest%2Fuser%2Fchange-password%3Fnew%3DslurmCl4ssic%26repeat%3DslurmCl4ssic\');%20xmlhttp.send()%3C%2Fscript%3E')
```

**Comment by bkimminich** [comment]
With 13ed0a6 Docker containers are now testable with the e2e suite. Automation still pending.

**Comment by bkimminich** [comment]
XXE Tier 2 test hangs Docker container just as it does Travis-CI job! ❌

```
    if (!process.env.TRAVIS_BUILD_NUMBER) {
      it('should be possible to trigger request timeout on Linux server via .xml upload with /dev/random XXE attack', () => {
        browser.waitForAngularEnabled(false)
        browser.executeScript(() => {
          const data = new FormData()
          const blob = new Blob(['<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///dev/random" >]><foo>&xxe;</foo>'], {type: 'application/xml'})
          data.append('file', blob, 'xxeDosForLinux.xml')

          const request = new XMLHttpRequest()
          request.open('POST', '/file-upload')
          request.send(data)
        })
        browser.driver.sleep(3000)
        browser.waitForAngularEnabled(true)
      })
    }
```
