### ISSUE TITLE
Segfault again on XML uploads

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#610]
Same as #449 uploading XML files can lead to segmentation fault errors during API test suite:

```
=============================== Coverage summary ===============================
Statements   : 0% ( 0/778 )
Branches     : 0% ( 0/490 )
Functions    : 0% ( 0/187 )
Lines        : 0% ( 0/760 )
================================================================================
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! juice-shop@7.3.0-SNAPSHOT frisby: `nyc --report-dir=./build/reports/coverage/api-tests jest --silent -i`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the juice-shop@7.3.0-SNAPSHOT frisby script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-06-12T20_41_58_466Z-debug.log
The command "travis_wait npm test && npm run frisby && NODE_ENV=ctf npm run protractor" exited with 139.
```

**Comment by ryanvillarreal** [comment]
The Docker version of Juice Shop is still throwing the segfault.  I did a pull latest today and it's still crashing on xml upload.  Is this something I can fix on my end?

**Comment by bkimminich** [comment]
Could you please pull the `snapshot` image and see if it happens there as well?

**Comment by ryanvillarreal** [comment]
Pulled the latest snapshot.  It works there, but the application did throw an error.  Not sure if that's expected or not.  

````
Error: B2B customer complaints via file upload have been deprecated for security reasons: Start tag expected, '<' not found
 (test.xml)
    at /juice-shop/routes/fileUpload.js:41:18
    at Layer.handle [as handle_request] (/juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at next (/juice-shop/node_modules/express/lib/router/route.js:137:13)
    at Array.<anonymous> (/juice-shop/node_modules/multer/lib/make-middleware.js:53:37)
    at listener (/juice-shop/node_modules/on-finished/index.js:169:15)
    at onFinish (/juice-shop/node_modules/on-finished/index.js:100:5)
    at callback (/juice-shop/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/juice-shop/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.emit (events.js:180:13)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by bkimminich** [comment]
That looks like your XML syntax was not appreciated by the parser. As long as the segfault is gone, all should be fine.
