### ISSUE TITLE
Check runtime environement on startup

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#683]
Run some checks on startup to check if the runtime environment is properly set up. These checks could include things like:

- [x] Checking that the Node Version is supported
- [x] Checking if dependencies were dependencies were installed
- [ ] ~Checking if the XML Stuff working~
- [x] Checking if Port 3000 is already in use

If something was some to be missing / wrong we could log out the error and give the user some hints how to resolve them. This could reduce troubles for new users not familiar with the used technologies.

**Comment by bkimminich** [comment]
Node version support _should_ be checked because of the declaration in `package.json`, no? And the XML challenges are now automatically disabled when the app runs inside a Docker container.

Do the remaining points warrant an extra `start.bat` / `start.sh` script pair to be added and maintained? Any other things we might put in there?

**Comment by J12934** [comment]
The engines flag in the `package.json` only seems to check the engines field if you try to add a this package as a dependency to your project. So wont be checked for our use case as Juice Shop isn't a package.

Checking these things could be done directly in node. 
It would just have to be the very first thing we do. So no `.sh` or '.bat' scripts required.

**Comment by bkimminich** [comment]
Similar to the challenge validation and country codes check then, sounds good!

**Comment by agrawalarpit14** [comment]
Hi @bkimminich @J12934 For "Checking if dependencies were dependencies were installed" I was trying to use `const dependencyCheck = require('check-dependencies')`. 
The documentation for `check-dependencies` can be found it https://www.npmjs.com/package/check-dependencies.
But when I run it inside `lib/startup/validatePreconditions.js`. Before the program reaches my call to `dependencyCheck()`, the following error occurs(in this case I first deleted the folder portscanner from `node_modules` so actually an error occurs):
```
➜  juice-shop git:(develop) ✗ npm run serve

> juice-shop@8.5.0-SNAPSHOT serve /Users/arpit/juice-shop
> concurrently --kill-others "node app" "cd frontend && ng serve"

[0] Wed, 27 Mar 2019 09:14:43 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
[0] internal/modules/cjs/loader.js:583
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module 'portscanner'
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0]     at require (internal/modules/cjs/helpers.js:22:18)
[0]     at Object.<anonymous> (/Users/arpit/juice-shop/lib/startup/validatePreconditions.js:7:21)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0]     at require (internal/modules/cjs/helpers.js:22:18)
[0]     at Object.<anonymous> (/Users/arpit/juice-shop/server.js:74:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0]     at require (internal/modules/cjs/helpers.js:22:18)
[0]     at Object.<anonymous> (/Users/arpit/juice-shop/app.js:1:78)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
[0]     at startup (internal/bootstrap/node.js:283:19)
[0] node app exited with code 1
--> Sending SIGTERM to other processes..
[1] cd frontend && ng serve exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! juice-shop@8.5.0-SNAPSHOT serve: `concurrently --kill-others "node app" "cd frontend && ng serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juice-shop@8.5.0-SNAPSHOT serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
➜  juice-shop git:(develop) ✗
```
Can you please help in understanding it?

**Comment by J12934** [comment]
The check for uninstalled dependencies would have to be the very first thing done in the server.
Your code isn't reached, as it fails due to missing dependencies, before the check is run. Or at least i would assume so from the stacktrace.

**Comment by agrawalarpit14** [comment]
> The check for uninstalled dependencies would have to be the very first thing done in the server.
> Your code isn't reached, as it fails due to missing dependencies, before the check is run. Or at least i would assume so from the stacktrace.

Yes, I too realise that. So, should I make at happen as the first thing in `server.js`?
It gives me the required output but makes the code look bad. Should I put it in a separate file?

**Comment by J12934** [comment]
Maybe create a `validateDependencies.js` next to the other validation files.

**Comment by agrawalarpit14** [comment]
> Maybe create a `validateDependencies.js` next to the other validation files.

Sure I will proceed with that.
Thanks!!

**Comment by bkimminich** [comment]
I think we can ditch any extra check for the XML stuff, right? With `libxmljs` being checked by the dependencies test, all should be fine.
