### ISSUE TITLE
Cannot find module './clone.js'

### ISSUE THREAD

**Issue by lucasturci** [juice-shop/juice-shop#731]
Hello, I tried installing juice-shop using node, but I get this error

    > phantomjs-prebuilt@2.1.16 install /Users/Lucas/Dropbox/Escola/Ganesh/web/juice-shop/node_modules/phantomjs-prebuilt
    > node install.js

    internal/modules/cjs/loader.js:596
        throw err;
        ^

    Error: Cannot find module './clone.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
        at Function.Module._load (internal/modules/cjs/loader.js:520:25)
        at Module.require (internal/modules/cjs/loader.js:650:17)
        at require (internal/modules/cjs/helpers.js:20:18)
        at Object.<anonymous> (/Users/Lucas/Dropbox/Escola/Ganesh/web/juice-shop/node_modules/graceful-fs/graceful-fs.js:4:13)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
        at Module.load (internal/modules/cjs/loader.js:612:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
        at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/Lucas/.npm/_logs/2018-11-04T19_03_12_662Z-debug.log

**Environment:**
OS: Mac OS X El Capitan 10.11.6
Node: v11.1.0
npm: v6.4.1

**Steps I reproduced:**
Only
`npm install`
After cloning it from git.

I attached the debug log file
[debug.log](https://github.com/bkimminich/juice-shop/files/2546190/debug.log)

**Comment by bkimminich** [comment]
Juice Shop supports node.js 8, 9 and 10 at the moment. Of course 11 will be added at some point, but probably not before all pre-built dependencies (like `sqlite3` & `libxmljs`) have stable versions for node.js 11 available.

**Comment by lucasturci** [comment]
Actually, I first had this error with node.js version 10.3.0
I figured that since there was a newer version of node, updating might resolve the issue. But yeah, no..
I'd really appreciate if you could give me a hand, and if there is some info I can give you but didn't, please tell me!
Thanks in advance!
